# stuff to replace out
# ’ -> '
# ‘ -> '
# “ -> "
# ” -> "


* topics

** papers

*** Similar brain activation patterns for writing logographic and phonetic symbols in Chinese

    doi:10.1097/WNR.0b013e3282f0405b
    
*** human kin recognition

    trying to understand the stats. can we replicate them?

    based on Figure 2:

#+TBLNAME: kin
| type | question  | barcolor | expect | stderr | # self | N subjects | self / N |
|------+-----------+----------+--------+--------+--------+------------+----------|
| MZ   | sibling   | white    |     62 |      9 |     21 |       34.0 |       62 |
| DZ   | sibling   | white    |     67 |      8 |     24 |       36.0 |       67 |
| MZ   | emergency | gray     |     68 |      8 |     23 |       34.0 |       68 |
| DZ   | emergency | gray     |     58 |      9 |     21 |       36.0 |       58 |
#+TBLFM: $7=round($3*100/$6)

with this, we've reproduced the bargraph values

the conclusions are based on t-tests for those values


This gives the first result (t_69 = 2.2, p = 0.030)

#+BEGIN_SRC R :session rkin :var dkin=kin :results output
t.test(c(rep(1, 44), rep(0, 26)), mu=0.5)
#+END_SRC

#+RESULTS:
#+begin_example

	One Sample t-test

data:  c(rep(1, 44), rep(0, 26)) 
t = 2.2103, df = 69, p-value = 0.0304
alternative hypothesis: true mean is not equal to 0.5 
95 percent confidence interval:
 0.5125278 0.7446151 
sample estimates:
mean of x 
0.6285714
#+end_example


This gives the second result (t_69 = 2.5, p = 0.016)

#+BEGIN_SRC R :session rkin :var dkin=kin :results output
t.test(c(rep(1, 45), rep(0, 25)), mu=0.5)
#+END_SRC

#+RESULTS:
#+begin_example

	One Sample t-test

data:  c(rep(1, 45), rep(0, 25)) 
t = 2.4766, df = 69, p-value = 0.01572
alternative hypothesis: true mean is not equal to 0.5 
95 percent confidence interval:
 0.5277812 0.7579331 
sample estimates:
mean of x 
0.6428571
#+end_example

I was first wondering whether using a binomial test would be more proper. e.g.,

#+BEGIN_SRC R :session rkin :var dkin=kin :results output
binom.test(44, n=70)
#+END_SRC

#+RESULTS:
#+begin_example

	Exact binomial test

data:  44 and 70 
number of successes = 44, number of trials = 70, p-value = 0.04139
alternative hypothesis: true probability of success is not equal to 0.5 
95 percent confidence interval:
 0.5047659 0.7411302 
sample estimates:
probability of success 
             0.6285714
#+end_example


To replicate the first case. That's fine and all. Then it occured to me that

DZ twins are essentially just identically aged-non-twins. They are actually collapsing across the MZ/DZ groups to get the results. Therefore, at best, we should look at the MZ group only.

The highest detection group (gray = emergency) would be

#+BEGIN_SRC R :session rkin :var dkin=kin :results output
binom.test(23, n=34)
#+END_SRC

#+RESULTS:
#+begin_example

	Exact binomial test

data:  23 and 34 
number of successes = 23, number of trials = 34, p-value = 0.05761
alternative hypothesis: true probability of success is not equal to 0.5 
95 percent confidence interval:
 0.4947347 0.8261166 
sample estimates:
probability of success 
             0.6764706
#+end_example

The graph is visually very impressive. The standard errors can be obtained from the t-test of say =t.test(c(rep(1, 21), rep(0, 13)), mu=0.5)= via =(0.7897572 - 0.4455369) * 100 / 3.92=, or 8.78.

For one then, the DZ gray bar is most suspect. The MZ may or may not pan out. It is better considered a group showing borderline significance above chance. Overall, it gives merit to the idea but I can't walk away convinced that this paper alone is enough to show it. Intruiging? Definitely.


*** Atherton et al -- A Functional MRI Study of High-Level Cognition. I. The Game of Chess

    [[doi:10.1016/S0926-6410(02)00207-0]]

    this paper is interesting in that its cites the same group's GO paper in its dicsussion. it's an amusing cycle in the reference.

**** TODO retrieve images -- the ~-B~ comment needs context

**** background quote

     #+BEGIN_QUOTE
     Cranberg and Albert hypothesized that chess ability is specialized in the right hemisphere, partly because they found high rates of left-handedness among serious players.     
     #+END_QUOTE

     - L.D. Cranberg, M.L. Albert, The chess mind, in: L. Kober, D. Fein (Eds.), The Exceptional Brain: Neuropsychology of Talent and Special Abilities, The Guilford Press, New York, 1988, pp. 156– 190.     

**** methods

     - 30s per block block-design

***** game condition

      #+BEGIN_QUOTE
      Middlegame positions were selected from De Firmian and Korn by an experienced player who judged them to be of approximately equal complexity. The total number of pieces per board ranged from 25 to 30 with an average of 27.1 pieces per presentation. The total number of pieces was equal for each contemporaneous pair of game and random presentations. Subjects were asked to determine the next best move for White.
      #+END_QUOTE

      - N. De Firmian, W. Korn (Eds.), Modern Chess Openings: MCO-13, 13th Edition, David McKay, New York, 1990.      

***** random condition

      #+BEGIN_QUOTE
      The placement of pieces in the middle of squares was avoided, because during pilot testing subjects indicated that such placement initiated thoughts of possible moves.
      #+END_QUOTE
      
**** fmri results

     surprising lack of hippocampus in -B conditions; but given that block was 30s, may have equalized


**** discussion

***** parietal lobes

      #+BEGIN_QUOTE
      areas of the parietal lobes are involved in numeric comparison [16] and approximation [6], as well as complex spatial tasks such as mental rotation [17].
      #+END_QUOTE

[6] S. Dehaene, E. Spelke, P. Pinel, R. Stanescu, S. Tsivkin, Sources of mathematical thinking: behavioral and brain-imaging evidence, Science 284 (1999) 970–974.

[16] P. Pinel, S. Dehaene, D. Riviere, D. LeBihan, Modulation of parietal activation by semantic distance in a number comparison task, NeuroImage 14 (2001) 1013–1026.

[17] W. Richter, K. Ugurbil, A. Georgopoulos, S. Kim, Time-resolved fMRI of mental rotation, NeuroReport 8 (1997) 3697–3702.


***** spearman's g

      #+BEGIN_QUOTE
      Spearman's g, which is characterized as a single factor underlying performance on cognitive tasks (rather than drawing on a diverse set of skills)
      #+END_QUOTE

      sounds like an old fashioned view. is there an update?

***** vs Go study

      #+BEGIN_QUOTE
      the main difference between the two studies was activation observed in area 44 for some of the Go subjects.
      #+END_QUOTE

      #+BEGIN_QUOTE
      Another important result is the lack of significant hemispheric lateralization in the current study
      #+END_QUOTE

*** M. S. Harre et al -- The Aggregate Complexity of Decisions in the Game of Go

    doi:10.1140/epjb/e2011-10905-8

    this paper is interesting in that it cites the Chess paper in its discussion, an amusing cycle in the reference

**** methods

     #+BEGIN_QUOTE
     Six male university students, all amateur players of GO with skill levels from level 1K to 1D (nonprofessional ranking) participated in the study.
     #+END_QUOTE
     
***** random board condition

      #+BEGIN_QUOTE
      Subjects were instructed to search for the stones with low contrast dots among the 30 stones (visual search task).
      #+END_QUOTE


**** background quote

     #+BEGIN_QUOTE
     (1) the storage component of spatial working memory is biased in the right parietal areas [16,19]
     #+END_QUOTE

     - [16] E.E. Smith, J. Jonides, Working memory: A view from neuroimaging, Cogn. Psychol. 33 (1997) 5–42.
     - [19] L.G. Ungerleider, S.M. Courtney, J.V. Haxby, A neural system for human visual working memory, Proc. Natl. Acad. Sci. USA 95 (1998) 883–890.


     #+BEGIN_QUOTE
     left BA44 / 45 is usually involved in language functions [2]
     #+END_QUOTE
     
     - [2] R. Cabeza, L. Nyberg, Imaging cognition II: An empirical review of 275 PET and fMRI studies, J. Cogn. Neurosci. 12 (1) (2000) 1–47.

     #+BEGIN_QUOTE
     BA30 / 31, important for episodic memory retrieval [2], was active in the GO task.
     #+END_QUOTE

     #+BEGIN_QUOTE
     The second issue is the involvement in GO playing of the so-called general intelligence ('g') areas recently roposed by Duncan and colleagues [6].
     #+END_QUOTE

     - [6] J. Duncan, R.J. Seitz, J. Kolodny et al., A neural basis for general intelligence, Science 289 (2000) 457–460.

     #+BEGIN_QUOTE
     more intelligent people often show less frontal activation when they are performing analytical tasks [17].
     #+END_QUOTE
       
     - [17] R.J. Sternberg, Cognition: The holey grail of general intelligence, Science 289 (2000) 399–401.

**** results

     #+BEGIN_QUOTE
     The only noticeable difference between the two games is that playing GO may involve BA44 / 45 but playing chess may not.
     #+END_QUOTE


*** Recall of rapidly presented random chess positions is a function of skill

**** background

     #+BEGIN_QUOTE
     A classical result in the study of expertise is that experts
are better than nonexperts at memorizing meaningful material from their domain of expertise, but lose their superiority when the material is randomized. This result was first obtained in the study of chess memory (Chase & Simon, 1973b; Jongman & Lemmens, cited in Vicente & De Groot, 1990) and has since been widely cited in cognitive psychology textbooks (see, e.g., Anderson, 1990;
Lesgold, 1988) and hailed as one of the cornerstones of the study of expertise (Saariluoma, 1989).
     #+END_QUOTE

     #+BEGIN_QUOTE
     Simon and Chase (1973) have proposed that 10,000h, or about 10 years, of intense practice and study are necessary to reach a high level of expertise.
     #+END_QUOTE

     on the topic of

     #+BEGIN_QUOTE
     the general view among students of expert memory has been that there is nodifference in recall with the standard presentation time of 5 sec
     #+END_QUOTE

     #+BEGIN_QUOTE
     In all cases, except in Chase and Simon's (1973b) study, recall performance increases monotonically as a function of skill.
     ...
     the strongest skill group out performed the weakest in 12 cases out of 13.
     #+END_QUOTE

**** meta analysis

     #+BEGIN_QUOTE
     skill difference in recall with random positions is small (roughly one piece per additional 400 ELO points), much less than for the recall of game positions, where an increase of 400 ELO points typically yields an increase of about five pieces.
     #+END_QUOTE
     
     (there's a plot here)

**** best candidate explanation

     #+BEGIN_QUOTE
     a large database of chunks in LTM, occasionally allowing the recognition of stored patterns that occur by chance in random positions
     #+END_QUOTE

     an agreeable explanation

*** Perception in Chess

    their interpretation of the results from de Groot 1965 & 1966 is nicely stated

    #+BEGIN_QUOTE
    Specifically, if a chess master can remember the location of 20 or more pieces on the board, but has space for only about five chunks in short-term memory, then each chunk must be composed of four or five pieces, organized in a single relational structure.
    #+END_QUOTE

    citations on prior studies involving eye movements wrt the chess board
    
    - de Groot, Adriaan D. "Perception and memory versus thought: Some old ideas and recent findings." Problem solving (1966): 19-50.
    - Simon, Herbert A., and Michael Barenfeld. "Information processing analysis of perceptual processes in problem solving." Psychological Review 76.5 (1969): 473-483.
    - Tikhomirov, O. K., and E. D. Poznyanskaya. "An investigation of visual search as a means of analyzing heuristics." Journal of Russian and East European Psychology 5.2 (1966): 3-15.
    - Winikoff, Arnold W. Eye movements as an aid to protocol analysis of problem solving behavior. Diss. Carnegie-Mellon University, 1967.

**** background information

     #+BEGIN_QUOTE
     Dansereau (1969), studying times of performance of mental arithmetic and related tasks, estimated that about 2 sec was needed to begin processing a chunk whose label was held in short-term memory, and only about 300 msec to transfer to short-term memory each successive element of the chunk. Intervals even shorter than 300 msec intervals are familiar from other experiments on the speed with which subjects can count down familiar lists (Landauer, 1962; Pierce & Karlin, 1957). 
     #+END_QUOTE


**** methods

     3 subjects!

     motivation

     #+BEGIN_QUOTE
     In the perception task, we ask chess players to reconstruct a chess position while it remains in plain view, and we use subjects' successive glances at the board as an index of chunking. The basic assumption is that, under the conditions of the experiment, the subject will encode only one chunk per glance while reconstructing the position.
     #+END_QUOTE

     #+BEGIN_QUOTE
     hypothesis that long pauses would correspond to boundaries between successive chunks, while short time intervals between pieces would indicate that the pieces belonged to the same chunk in memory. 
     #+END_QUOTE

**** results

     #+BEGIN_QUOTE
     from the within-glance relations, it appears that subjects are noticing the pawn structure, clusters of pieces of the same color, and attack and defense relations over small spatial distances. 
     #+END_QUOTE

     i.e., chunking is facilitated by spatial proximity. Not surprising, but speaks against the notion that if we have a master, they are chunking the board -- though, it could be possible, with a large enough repertoire. The point being that what's observed here is within expectation of skill mastery.

     from Chess Relations for Random Positions (table 3):

     #+BEGIN_QUOTE
     subjects are noticing the same kinds of structures in the random positions as in the game positions even though such structures are rare in the random positions.
     #+END_QUOTE
     
     i.e. the same chunking strategies are being used when confronted with an unfamiliar setup.

     Very nice: Figure 5 shows interpiece latencies vs. number of relations {A, P, C, S, D} between pairs.

     #+BEGIN_QUOTE
     For the middle-game positions, the average number of pieces per glance was 2.0, 2.8, and 2.0, respectively, for M, A, and B. For the memory experiment, however, the corresponding number of pieces per chunk was 2.5, 2.1, and 1.9, respectively. Thus, it appears that the chunks are about the same size in both tasks, but that chess skill is reflected in the speed with which chunks are perceived in the perception task and the size of the chunks in the memory task.
     #+END_QUOTE

     #+BEGIN_QUOTE
     M achieves his superior performance by recalling both more chunks and larger chunks.
     #+END_QUOTE

     (chunks are identified by "two or more pieces within 2 sec")

     The general estimate of the vocabulary size for the master subject is something around a half dozen classic / stereotyped positions.
     
***** reconstruct the table?


***** interview

      #+BEGIN_QUOTE
      M, when interviewed after the experiment, reported that he was troubled by positions that looked "unreasonable." He also reported difficulty with positions that were not quiet, complaining that he couldn't get the "sense" of the position when it was in the middle of an exchange. 
      #+END_QUOTE

      #+BEGIN_QUOTE
      M recognized four of the nine new positions, and always within the first second of exposure
      #+END_QUOTE

      
*** Structure and Stimulus Familiarity A Study of Memory in Chess-Players with fMRI

    Campitelli et al

**** background

     #+BEGIN_QUOTE
     [chess players] maintained their level of performance in memory tasks when less familiar symbols were used to represent the position (i.e., the use of the initial of the name of the chess piece on the board, instead of the normal symbol that represents the piece
     #+END_QUOTE

     that is citing Chase and Simon (1973)

     #+BEGIN_QUOTE
     The templates theory was implemented in a computer model—CHREST (Gobet & Jansen, 1994)—that contains a "mental eye," a short-term memory, and a long-term memory. The mental eye allows the formation of mental images, either from retina stimulation or from the activation of information in memory. The short-term memory is a vector with a capacity for 4 items, and the long-term memory contains a discrimination network in which chunks and templates are formed by means of familiarization and discrimination processes. This model has successfully simulated the performance of chess-players of different levels in memory tasks (Gobet & Simon, 2000), as well as the chess-players’ eye-movements (De Groot & Gobet, 1996). It has also simulated problem-solving in computer programmers (Lane, Cheng, & Gobet, 2001) and language acquisition (Gobet et al., 2001)
     #+END_QUOTE

     #+BEGIN_QUOTE
     Nichelli and colleagues (1994) found brain activation in the left middle temporal lobe in a task that consisted of determining whether or not a move was legal. Onofrj et al. (1995) and Atherton, Zhuang, Bart, Hu, and Sheng (2003) studied chess-players who had to solve a chess problem while their brain activity was recorded. Onofrj et al. found brain activity in the nondominant superior frontal lobe and medial temporal lobe (that is, the right hemisphere in right-handed individuals and the left one in left-handed individuals). Atherton et al. found left hemisphere activation in the superior frontal lobe and cerebellum, and bilateral activation in the precuneus and posterior cingulate cortex. Lastly, Amizdic, Riehle, Fehr, Wienbruch, and Elbert, (2001) obtained brain images of chess-players while they played a game against a computer. They found a different distribution of brain activation in masters as compared with players of a lower level. The former showed a relatively more extended activation pattern in the frontal and parietal lobes than in medial temporal areas, whereas the lower level chess-players showed a relatively opposite distribution
     #+END_QUOTE

     #+BEGIN_QUOTE
     tasks requiring a greater cognitive demand, such as solving a chess problem or playing a game of chess, tend to activate frontal and parietal areas (Amizdic et al., 2001; Atherton et al., 2003; Onofrj et al., 1995). Conversely, tasks that require the mere retrieval of relevant information, such as chess rules, tend to activate temporal areas (Nichelli et al., 1994)
     #+END_QUOTE

     

**** method

     setup of the task is essentially a 1-back task. unfortunately there wasn't a "logically same" condition, which compares whether the trial condition is logically the same as the reference board (this would be tricky though; it would require something like 1. a logically same condition where all pieces are changed -- otherwise it would be the "identical" condition; 2. a rotation condition, with/without piece appearance changes, plus foil pieces such that a simple rotation would not sufficiently determine logical equality; then for 2. again, a contrast of mental rotation condition is a further requirement).

     for the novices, a legal vs. illegal chess board would not carry as much "meaning" as it would for experts. the setup using 1-back then is a contrast of *automatized vs non-automatized* processes. for the novices, since chessboard processing is *non-automatized*, the 1-back task results should display activations like a visual comparison task (as in a pure visual process), a short term memory task (as in what should be expected in a standard 1-back task regardless of stimulus modality), a visual search task (authors recognize the possibiilty of the delay period being a "visual review" in discussion), and to a small extent a LTM retrieval task (matching pieces to rules/roles, especially in the position-scene condition).


**** results

     anecdote on 2 master subjects on memorizing the geometric correspondence

     #+BEGIN_QUOTE
     The two masters commented to the experimenter that they easily memorized the correspondence of the geometric figures with chess pieces, and this was facilitated by the similarity between the figures and the pieces, and that during the experiment, they perceived the figures as if they were chess pieces.
     #+END_QUOTE

     unfortunately we can't tell how much the memorization of the correspondence was facilitated by the similarity of chess pieces. Though intuitively, maximal discruption could be achieved if we simply shuffled pieces for the mapping (e.g. Pawns to Rooks, Rooks to Kings, etc.). The interesting and unanswered case here is for a minimally disruptive but minimally informative mapping (say, blobs), how easy would the mapping be, and what happens on a correct mapping?

     A possibility if we use random blobs is there's a mental burden of recalling the blob -> piece correspondence, which should be shared across novices and experts as a simple paired-associate learning task. The question is whether expert LTM of spatial arrangements and logical positions actually facilitates remembering. But that would be similar to say, decoding ROT13 (or any substitution cipher) for an average English speaker. Thus I'd believe that the geometric similarity is highly important. So the reference to Chase and Simon (1973), where they used the initials of the pieces, probably still demonstrates domain specific memory.
     
     regarding result of "brain activation in frontal areas of the novices but not in the masters":
     
     #+BEGIN_QUOTE
     the masters' familiarity with the chess symbols resulted in their not generating any additional processing demand
     #+END_QUOTE

     #+BEGIN_QUOTE
      in contrast to the masters, the novices require high activation in frontal areas in the chess position condition, which suggests a switch in the masters’ type of processing, from anterior to posterior areas of the brain.
     #+END_QUOTE
     
     
*** The neural organization of perception in chess experts

    Krawczyk et al

    doi:10.1016/j.neulet.2011.05.033

**** background

     #+BEGIN_QUOTE
     the fusiform is considered to be a neural marker of visual expertise, as other studies have reported selective fusiform activity when car experts and bird experts perceive cars and birds and when radiologists examine scans [12,27,17].
     #+END_QUOTE

     #+BEGIN_QUOTE
     A recent documentary film showed a neuroimaging clip with a chess expert and suggested that the face-selective fusiform can be "hijacked" to process chess patterns [23].
     #+END_QUOTE

     [23] K. Scott, (Producer/Director) My Brilliant Brain: Make Me a Genius [Television series episode]. London, 2007, Windfall Films

     This is the show where they scanned Susan Polgar's brain

     #+BEGIN_QUOTE
     Words have been shown to produce highly specific neural effects that depend on specific configurations, such as the presence of vowels versus consonants [5].
     #+END_QUOTE

     [5] M. Carreiras, J.A. Du˜nabeitia, N. Molinaro, Consonants and vowels contribute differently to visual word recognition: ERPs of relative position priming, Cereb. Cortex 19 (2009) 2659–2670.
     
     #+BEGIN_QUOTE
     Dehaene et al. [8] recently reported that reading experience shows evidence of domain general effects in V1, temporal, and fusiform cortex, as literacy increased overall neural responses in these areas.
     #+END_QUOTE

     [8] S. Dehaene, F. Pegado, L.W. Braga, P. Ventura, G.N. Filho, A. Jobert, G. Dehaene-Lambertz, R. Kolinsky, J. Morais, L. Cohen, How learning to read changes the cortical networks for vision and language, Science 330 (2010) 1359–1364

**** methods

     #+BEGIN_QUOTE
     These subjects ranked within the top one percent of tournament players (five International Masters, one Grandmaster). Their expertise was substantiated by their com-petitive ratings (Elo range = 2447–2583; M = 2515), years playing (M = 16 years), and tournament activity (M = 17 per year)
     #+END_QUOTE

     The years playing is a potentially interesting confound; the mean age of participants here is 23; for the expert level subjects then the mean start age is around 7 years old. We should expect substantial plasticity during this age and resulting cortical reorganization that cannot be observed from training adults for the same duration.

     #+BEGIN_QUOTE
     Images were presented off-set from center to the right or left in an alternating sequence to avoid apparent motion effects in the chess conditions between non-matching items in sequence.
     #+END_QUOTE

     good idea.

     #+BEGIN_QUOTE
     chess minus random chess contrast between groups ... showed no significant clusters in novices. In experts, this contrast resulted in two clusters within the posterior cingulate (MNI coordinates: x = 32, y = 10, z = 12) and the right insula (x = 12, y = -50, z = 10).
     #+END_QUOTE
     
**** results

     #+BEGIN_QUOTE
     The experts indicated that they could perceive all or most of the chess boards within 2 s. Several reported that random chess was more difficult to perceive than real chess. Novices reported that they could rarely perceive all of the pieces and none reported that they were aware that the random games were impossible according to the rules of chess, a distinction all experts readily reported.
     #+END_QUOTE

     #+BEGIN_QUOTE
     The only significant group difference was that experts (M = 97.92%, SD = 3.23) were more accurate at detecting repeats of chess boards than novices (M = 87.50%, SD = 13.69).
     #+END_QUOTE

     #+BEGIN_QUOTE
     We directly compared the groups on the chess minus random chess contrast using a random-effects fMRI group analysis (uncorrected p < .001, 20 voxel minimum) (refer to Fig. 1B and C). Significant differences emerged with experts showing greater activation in the left orbitofrontal cortex (x = -4, y = 58, z = -2), in the left (x = -10, y = -50, z = 12) and right posterior cingulate (x = 14, y = -52, z = 2), and in the left anterior temporal cortex (x = -50, y = 8, z = -26). By contrast, the novices showed greater activation than experts in two distinct clusters in right parietal cortex (x = -32, y = -52, z = 40) and (x = -38, y = -54, z = 46).
     #+END_QUOTE

     The seemingly across-the-board lower activation in the left FFA for experts compared to novices (also Right FFA, though probably visually insignificant) is very curious. I don't see this being addressed directly in the paper but definitely looks worth digging into.

     #+BEGIN_QUOTE
     There may be instances in which face-sensitive areas respond to chess stimuli [21,24], but our results indicate that this does not reflect basic perceptual processing of the type that was examined in the present study and in most prior studies that have established the existence of the fusiform face area [13,18]
     #+END_QUOTE

     #+BEGIN_QUOTE
     we did not observe clear reductions in FFA activation either in chess experts or in chess novices. Such a finding would be consistent with neural plasticity dedifferentiating standard face expertise responses [8,22].
     #+END_QUOTE

     [22] B. Rossion, C.C. Kung, M.J. Tarr, Visual expertise with nonface objects leads to competition with the early perceptual processing of faces in the human occipitotemporal cortex, Proc. Natl. Acad. Sci. U.S.A. 101 (2004) 14521-14526.
     
**** conclusion

     #+BEGIN_QUOTE
     Our results are most consistent with the position that chess and face expertise are processed independently as measured by modulation of fusiform responses in experts ... cortical regions sensitive to face processing showed face selectivity without overlap with chess.
     #+END_QUOTE

     #+BEGIN_QUOTE
     There was some differential activation of the left parietal cortex in novices over experts associated with real game chess processing. The parietal lobes have been associated with spatial processing previously [3], suggesting that this activation may have been related to a greater level of visual location search than occurred for the expert group. The left temporo-parietal junction showed evidence of chess modulation in experts. This is an area that has been associated with integration of visual features, thus providing the clearest evidence of a perceptually driven neural change related to chess expertise.
     #+END_QUOTE

     [3] G. Campitelli, F. Gobet, K. Head, M. Buckley, A. Parker, Brain localization of memory chunks in chess players, Int. J. Neurosci. 117 (2007) 1641–1659


** books

   Exit, Voice, and Loyalty

   The Economies of Cities


** probability matching

[[file:probability-matching.org]]


* assorted

** voiceless velar fricative

   http://en.wikipedia.org/wiki/Voiceless_velar_fricative

   it lists Chinese "he2" as an example. I suspect this is region-specific and probably time-specific too.

* A Conversation with Elon Musk

  https://www.youtube.com/watch?v=vDwzmJpI4io

** Mars Oasis concept

17:18 the public responds to precedents and superlatives. So, we're the first life on mars, the farthest that life's ever traveled, and you have this money shot of green plants on a red background. So, that seemed like it would get people pretty excited.

34:00 the nature of new technology adoption is it tends to follow an S-curve. so what usually happens is people underpredict in the beginning, because people tend to extrapolate on a straight line, and then they will overpredict it kind of at the midpoint because there's late adopters, and it will actually take longer than people think at the midpoint, but much shorter than people think at the beginning.

** QA 1: on startups and profits

   a lot of times people think creating companies is gonna be fun.

   i would say it's really not that fun. there are periods of fun, and there are periods where it's just awful.

   and particularly if you're the CEO of the company, you actually have a distillation of all the worst problems in the company. there's no point in spending your time on things that are going right, so you're only spending your time on things that are going wrong.

   and there are things that are going wrong that other people can't take care of. so you have like the worst -- you have a filter for the crappest problems in the company. the most pernicious and painful problems.

   

** QA 2: on the hyperloop

   so if we had something like the hyperloop, they would be like, cool!, you look forward to the day that that was working.
   even if it were only in one place (LA to SFO, or NY to DC or something like that). it would be cool enough that it would be like a tourist attraction.
   ... when you come up with a new technology, it should feel like that. if you told it to an objective person, would they look forward to the day that that thing became available.

   
