# stuff to replace out
# ’ -> '
# ‘ -> '
# “ -> "
# ” -> "


* topics

** papers

*** Similar brain activation patterns for writing logographic and phonetic symbols in Chinese

    doi:10.1097/WNR.0b013e3282f0405b
    
*** human kin recognition

    trying to understand the stats. can we replicate them?

    based on Figure 2:

#+TBLNAME: kin
| type | question  | barcolor | expect | stderr | # self | N subjects | self / N |
|------+-----------+----------+--------+--------+--------+------------+----------|
| MZ   | sibling   | white    |     62 |      9 |     21 |       34.0 |       62 |
| DZ   | sibling   | white    |     67 |      8 |     24 |       36.0 |       67 |
| MZ   | emergency | gray     |     68 |      8 |     23 |       34.0 |       68 |
| DZ   | emergency | gray     |     58 |      9 |     21 |       36.0 |       58 |
#+TBLFM: $7=round($3*100/$6)

with this, we've reproduced the bargraph values

the conclusions are based on t-tests for those values


This gives the first result (t_69 = 2.2, p = 0.030)

#+BEGIN_SRC R :session rkin :var dkin=kin :results output
t.test(c(rep(1, 44), rep(0, 26)), mu=0.5)
#+END_SRC

#+RESULTS:
#+begin_example

	One Sample t-test

data:  c(rep(1, 44), rep(0, 26)) 
t = 2.2103, df = 69, p-value = 0.0304
alternative hypothesis: true mean is not equal to 0.5 
95 percent confidence interval:
 0.5125278 0.7446151 
sample estimates:
mean of x 
0.6285714
#+end_example


This gives the second result (t_69 = 2.5, p = 0.016)

#+BEGIN_SRC R :session rkin :var dkin=kin :results output
t.test(c(rep(1, 45), rep(0, 25)), mu=0.5)
#+END_SRC

#+RESULTS:
#+begin_example

	One Sample t-test

data:  c(rep(1, 45), rep(0, 25)) 
t = 2.4766, df = 69, p-value = 0.01572
alternative hypothesis: true mean is not equal to 0.5 
95 percent confidence interval:
 0.5277812 0.7579331 
sample estimates:
mean of x 
0.6428571
#+end_example

I was first wondering whether using a binomial test would be more proper. e.g.,

#+BEGIN_SRC R :session rkin :var dkin=kin :results output
binom.test(44, n=70)
#+END_SRC

#+RESULTS:
#+begin_example

	Exact binomial test

data:  44 and 70 
number of successes = 44, number of trials = 70, p-value = 0.04139
alternative hypothesis: true probability of success is not equal to 0.5 
95 percent confidence interval:
 0.5047659 0.7411302 
sample estimates:
probability of success 
             0.6285714
#+end_example


To replicate the first case. That's fine and all. Then it occured to me that

DZ twins are essentially just identically aged-non-twins. They are actually collapsing across the MZ/DZ groups to get the results. Therefore, at best, we should look at the MZ group only.

The highest detection group (gray = emergency) would be

#+BEGIN_SRC R :session rkin :var dkin=kin :results output
binom.test(23, n=34)
#+END_SRC

#+RESULTS:
#+begin_example

	Exact binomial test

data:  23 and 34 
number of successes = 23, number of trials = 34, p-value = 0.05761
alternative hypothesis: true probability of success is not equal to 0.5 
95 percent confidence interval:
 0.4947347 0.8261166 
sample estimates:
probability of success 
             0.6764706
#+end_example

The graph is visually very impressive. The standard errors can be obtained from the t-test of say =t.test(c(rep(1, 21), rep(0, 13)), mu=0.5)= via =(0.7897572 - 0.4455369) * 100 / 3.92=, or 8.78.

For one then, the DZ gray bar is most suspect. The MZ may or may not pan out. It is better considered a group showing borderline significance above chance. Overall, it gives merit to the idea but I can't walk away convinced that this paper alone is enough to show it. Intruiging? Definitely.


*** Atherton et al -- A Functional MRI Study of High-Level Cognition. I. The Game of Chess

    [[doi:10.1016/S0926-6410(02)00207-0]]

    this paper is interesting in that its cites the same group's GO paper in its dicsussion. it's an amusing cycle in the reference.

**** TODO retrieve images -- the ~-B~ comment needs context

**** background quote

     #+BEGIN_QUOTE
     Cranberg and Albert hypothesized that chess ability is specialized in the right hemisphere, partly because they found high rates of left-handedness among serious players.     
     #+END_QUOTE

     - L.D. Cranberg, M.L. Albert, The chess mind, in: L. Kober, D. Fein (Eds.), The Exceptional Brain: Neuropsychology of Talent and Special Abilities, The Guilford Press, New York, 1988, pp. 156– 190.     

**** methods

     - 30s per block block-design

***** game condition

      #+BEGIN_QUOTE
      Middlegame positions were selected from De Firmian and Korn by an experienced player who judged them to be of approximately equal complexity. The total number of pieces per board ranged from 25 to 30 with an average of 27.1 pieces per presentation. The total number of pieces was equal for each contemporaneous pair of game and random presentations. Subjects were asked to determine the next best move for White.
      #+END_QUOTE

      - N. De Firmian, W. Korn (Eds.), Modern Chess Openings: MCO-13, 13th Edition, David McKay, New York, 1990.      

***** random condition

      #+BEGIN_QUOTE
      The placement of pieces in the middle of squares was avoided, because during pilot testing subjects indicated that such placement initiated thoughts of possible moves.
      #+END_QUOTE
      
**** fmri results

     surprising lack of hippocampus in -B conditions; but given that block was 30s, may have equalized


**** discussion

***** parietal lobes

      #+BEGIN_QUOTE
      areas of the parietal lobes are involved in numeric comparison [16] and approximation [6], as well as complex spatial tasks such as mental rotation [17].
      #+END_QUOTE

[6] S. Dehaene, E. Spelke, P. Pinel, R. Stanescu, S. Tsivkin, Sources of mathematical thinking: behavioral and brain-imaging evidence, Science 284 (1999) 970–974.

[16] P. Pinel, S. Dehaene, D. Riviere, D. LeBihan, Modulation of parietal activation by semantic distance in a number comparison task, NeuroImage 14 (2001) 1013–1026.

[17] W. Richter, K. Ugurbil, A. Georgopoulos, S. Kim, Time-resolved fMRI of mental rotation, NeuroReport 8 (1997) 3697–3702.


***** spearman's g

      #+BEGIN_QUOTE
      Spearman's g, which is characterized as a single factor underlying performance on cognitive tasks (rather than drawing on a diverse set of skills)
      #+END_QUOTE

      sounds like an old fashioned view. is there an update?

***** vs Go study

      #+BEGIN_QUOTE
      the main difference between the two studies was activation observed in area 44 for some of the Go subjects.
      #+END_QUOTE

      #+BEGIN_QUOTE
      Another important result is the lack of significant hemispheric lateralization in the current study
      #+END_QUOTE

*** M. S. Harre et al -- The Aggregate Complexity of Decisions in the Game of Go

    doi:10.1140/epjb/e2011-10905-8

    this paper is interesting in that it cites the Chess paper in its discussion, an amusing cycle in the reference

**** methods

     #+BEGIN_QUOTE
     Six male university students, all amateur players of GO with skill levels from level 1K to 1D (nonprofessional ranking) participated in the study.
     #+END_QUOTE
     
***** random board condition

      #+BEGIN_QUOTE
      Subjects were instructed to search for the stones with low contrast dots among the 30 stones (visual search task).
      #+END_QUOTE


**** background quote

     #+BEGIN_QUOTE
     (1) the storage component of spatial working memory is biased in the right parietal areas [16,19]
     #+END_QUOTE

     - [16] E.E. Smith, J. Jonides, Working memory: A view from neuroimaging, Cogn. Psychol. 33 (1997) 5–42.
     - [19] L.G. Ungerleider, S.M. Courtney, J.V. Haxby, A neural system for human visual working memory, Proc. Natl. Acad. Sci. USA 95 (1998) 883–890.


     #+BEGIN_QUOTE
     left BA44 / 45 is usually involved in language functions [2]
     #+END_QUOTE
     
     - [2] R. Cabeza, L. Nyberg, Imaging cognition II: An empirical review of 275 PET and fMRI studies, J. Cogn. Neurosci. 12 (1) (2000) 1–47.

     #+BEGIN_QUOTE
     BA30 / 31, important for episodic memory retrieval [2], was active in the GO task.
     #+END_QUOTE

     #+BEGIN_QUOTE
     The second issue is the involvement in GO playing of the so-called general intelligence ('g') areas recently roposed by Duncan and colleagues [6].
     #+END_QUOTE

     - [6] J. Duncan, R.J. Seitz, J. Kolodny et al., A neural basis for general intelligence, Science 289 (2000) 457–460.

     #+BEGIN_QUOTE
     more intelligent people often show less frontal activation when they are performing analytical tasks [17].
     #+END_QUOTE
       
     - [17] R.J. Sternberg, Cognition: The holey grail of general intelligence, Science 289 (2000) 399–401.

**** results

     #+BEGIN_QUOTE
     The only noticeable difference between the two games is that playing GO may involve BA44 / 45 but playing chess may not.
     #+END_QUOTE


*** Recall of rapidly presented random chess positions is a function of skill

**** background

     #+BEGIN_QUOTE
     A classical result in the study of expertise is that experts
are better than nonexperts at memorizing meaningful material from their domain of expertise, but lose their superiority when the material is randomized. This result was first obtained in the study of chess memory (Chase & Simon, 1973b; Jongman & Lemmens, cited in Vicente & De Groot, 1990) and has since been widely cited in cognitive psychology textbooks (see, e.g., Anderson, 1990;
Lesgold, 1988) and hailed as one of the cornerstones of the study of expertise (Saariluoma, 1989).
     #+END_QUOTE

     #+BEGIN_QUOTE
     Simon and Chase (1973) have proposed that 10,000h, or about 10 years, of intense practice and study are necessary to reach a high level of expertise.
     #+END_QUOTE

     on the topic of

     #+BEGIN_QUOTE
     the general view among students of expert memory has been that there is nodifference in recall with the standard presentation time of 5 sec
     #+END_QUOTE

     #+BEGIN_QUOTE
     In all cases, except in Chase and Simon's (1973b) study, recall performance increases monotonically as a function of skill.
     ...
     the strongest skill group out performed the weakest in 12 cases out of 13.
     #+END_QUOTE

**** meta analysis

     #+BEGIN_QUOTE
     skill difference in recall with random positions is small (roughly one piece per additional 400 ELO points), much less than for the recall of game positions, where an increase of 400 ELO points typically yields an increase of about five pieces.
     #+END_QUOTE
     
     (there's a plot here)

**** best candidate explanation

     #+BEGIN_QUOTE
     a large database of chunks in LTM, occasionally allowing the recognition of stored patterns that occur by chance in random positions
     #+END_QUOTE

     an agreeable explanation

*** Perception in Chess

    their interpretation of the results from de Groot 1965 & 1966 is nicely stated

    #+BEGIN_QUOTE
    Specifically, if a chess master can remember the location of 20 or more pieces on the board, but has space for only about five chunks in short-term memory, then each chunk must be composed of four or five pieces, organized in a single relational structure.
    #+END_QUOTE

    citations on prior studies involving eye movements wrt the chess board
    
    - de Groot, Adriaan D. "Perception and memory versus thought: Some old ideas and recent findings." Problem solving (1966): 19-50.
    - Simon, Herbert A., and Michael Barenfeld. "Information processing analysis of perceptual processes in problem solving." Psychological Review 76.5 (1969): 473-483.
    - Tikhomirov, O. K., and E. D. Poznyanskaya. "An investigation of visual search as a means of analyzing heuristics." Journal of Russian and East European Psychology 5.2 (1966): 3-15.
    - Winikoff, Arnold W. Eye movements as an aid to protocol analysis of problem solving behavior. Diss. Carnegie-Mellon University, 1967.

**** background information

     #+BEGIN_QUOTE
     Dansereau (1969), studying times of performance of mental arithmetic and related tasks, estimated that about 2 sec was needed to begin processing a chunk whose label was held in short-term memory, and only about 300 msec to transfer to short-term memory each successive element of the chunk. Intervals even shorter than 300 msec intervals are familiar from other experiments on the speed with which subjects can count down familiar lists (Landauer, 1962; Pierce & Karlin, 1957). 
     #+END_QUOTE


**** methods

     3 subjects!

     motivation

     #+BEGIN_QUOTE
     In the perception task, we ask chess players to reconstruct a chess position while it remains in plain view, and we use subjects' successive glances at the board as an index of chunking. The basic assumption is that, under the conditions of the experiment, the subject will encode only one chunk per glance while reconstructing the position.
     #+END_QUOTE

     #+BEGIN_QUOTE
     hypothesis that long pauses would correspond to boundaries between successive chunks, while short time intervals between pieces would indicate that the pieces belonged to the same chunk in memory. 
     #+END_QUOTE

**** results

     #+BEGIN_QUOTE
     from the within-glance relations, it appears that subjects are noticing the pawn structure, clusters of pieces of the same color, and attack and defense relations over small spatial distances. 
     #+END_QUOTE

     i.e., chunking is facilitated by spatial proximity. Not surprising, but speaks against the notion that if we have a master, they are chunking the board -- though, it could be possible, with a large enough repertoire. The point being that what's observed here is within expectation of skill mastery.

     from Chess Relations for Random Positions (table 3):

     #+BEGIN_QUOTE
     subjects are noticing the same kinds of structures in the random positions as in the game positions even though such structures are rare in the random positions.
     #+END_QUOTE
     
     i.e. the same chunking strategies are being used when confronted with an unfamiliar setup.

     Very nice: Figure 5 shows interpiece latencies vs. number of relations {A, P, C, S, D} between pairs.

     #+BEGIN_QUOTE
     For the middle-game positions, the average number of pieces per glance was 2.0, 2.8, and 2.0, respectively, for M, A, and B. For the memory experiment, however, the corresponding number of pieces per chunk was 2.5, 2.1, and 1.9, respectively. Thus, it appears that the chunks are about the same size in both tasks, but that chess skill is reflected in the speed with which chunks are perceived in the perception task and the size of the chunks in the memory task.
     #+END_QUOTE

     #+BEGIN_QUOTE
     M achieves his superior performance by recalling both more chunks and larger chunks.
     #+END_QUOTE

     (chunks are identified by "two or more pieces within 2 sec")

     The general estimate of the vocabulary size for the master subject is something around a half dozen classic / stereotyped positions.
     
***** reconstruct the table?


***** interview

      #+BEGIN_QUOTE
      M, when interviewed after the experiment, reported that he was troubled by positions that looked "unreasonable." He also reported difficulty with positions that were not quiet, complaining that he couldn't get the "sense" of the position when it was in the middle of an exchange. 
      #+END_QUOTE

      #+BEGIN_QUOTE
      M recognized four of the nine new positions, and always within the first second of exposure
      #+END_QUOTE

      

** books

   Exit, Voice, and Loyalty

   The Economies of Cities


** probability matching

[[file:probability-matching.org]]


* assorted

** voiceless velar fricative

   http://en.wikipedia.org/wiki/Voiceless_velar_fricative

   it lists Chinese "he2" as an example. I suspect this is region-specific and probably time-specific too.

* A Conversation with Elon Musk

  https://www.youtube.com/watch?v=vDwzmJpI4io

** Mars Oasis concept

17:18 the public responds to precedents and superlatives. So, we're the first life on mars, the farthest that life's ever traveled, and you have this money shot of green plants on a red background. So, that seemed like it would get people pretty excited.

34:00 the nature of new technology adoption is it tends to follow an S-curve. so what usually happens is people underpredict in the beginning, because people tend to extrapolate on a straight line, and then they will overpredict it kind of at the midpoint because there's late adopters, and it will actually take longer than people think at the midpoint, but much shorter than people think at the beginning.

** QA 1: on startups and profits

   a lot of times people think creating companies is gonna be fun.

   i would say it's really not that fun. there are periods of fun, and there are periods where it's just awful.

   and particularly if you're the CEO of the company, you actually have a distillation of all the worst problems in the company. there's no point in spending your time on things that are going right, so you're only spending your time on things that are going wrong.

   and there are things that are going wrong that other people can't take care of. so you have like the worst -- you have a filter for the crappest problems in the company. the most pernicious and painful problems.

   

** QA 2: on the hyperloop

   so if we had something like the hyperloop, they would be like, cool!, you look forward to the day that that was working.
   even if it were only in one place (LA to SFO, or NY to DC or something like that). it would be cool enough that it would be like a tourist attraction.
   ... when you come up with a new technology, it should feel like that. if you told it to an objective person, would they look forward to the day that that thing became available.

   
