* Reading Ability Is Negatively Related to Stroop Interference
  
  Athanassios Protopapas & Anastasia Archonti & Christos Skaloumbakas 2007

  [fn:protopapasetal2007reading]

** Stroop interference

   #+BEGIN_QUOTE
   can be taken as a measure of reading automaticity (Logan, 1997). Therefore, intuitively, reading skill should be
   expected to be positively correlated with Stroop interference, with better readers exhibiting stronger
   interference. Even though expression of such a general expectation is found in the literature (Samuels, 1999),
   certain research findings also exist that are difficult to reconcile with it (e.g., Everatt, Warner, & Miles, 1997)
   #+END_QUOTE


   #+BEGIN_QUOTE
   text-level automaticity has also been proposed (Logan, 1997; Samuels & Flor, 1997). This means that little eVort or
   attention is required to derive word meanings from the written letter strings. Thus, in skilled readers, sufficient
   cognitive resources are thought to be available for computation of the meaning of the text (Adams, 1990; LaBerge &
   Samuels, 1974; Samuels, 1999).
   #+END_QUOTE

** Automaticity

   #+BEGIN_QUOTE
   Automaticity does entail flawless and rapid processing of text, that is, increased speed and accuracy of reading,
   but, consistent with Logan's (1997) multi-component analysis, it is probably not a unitary construct in its
   application to reading development. Stanovich (1990) has separated the components of obligatoriness, speed, and
   resource limitations, arguing that even though skilled reading, being an automatic process, is seen as obligatory,
   fast, and resource-free at the same time, reading practice past the point of accurate decoding does not necessarily
   achieve these goals simultaneously. In particular, obligatoriness may develop quickly while speed may still lag
   behind.
   #+END_QUOTE

*** "fluency" is an ill-defined construct in literature

     #+BEGIN_QUOTE
     Complicating matters further, reading researchers often refer to reading "fluency," a term theoretically distinct
from "automaticity" (Kuhn & Stahl, 2003; Wolf & Katzir-Cohen, 2001) but in practice greatly overlapping, because fluency
is difficult to assess out- side the domains of reading speed and accuracy.
     #+END_QUOTE

** Automaticity and Obligatoriness in Stroop

   #+BEGIN_QUOTE
   MacLeod (1991) has reviewed the massive evidence from variants of this task and put a number of alternative
   hypothesis to the test of accounting for the data. Although none of the candidates was entirely successful, it
   seems that early notions of relative processing speed were inadequate, whereas the notion of automaticity was
   almost sufficient, especially in its modern, graded form (as opposed to the early binary distinction of controlled
   versus automatic processing). More recent proposals along the lines of parallel distributed processing seemed to
   fare best, as they apparently combine desirable aspects of both processing speed and an automaticity continuum.
   #+END_QUOTE

   ~reading the word is seen as obligatory, whereas naming the ink color is not~

   #+BEGIN_QUOTE
   reading is much more practiced than color naming and therefore reading dominates naming without regard for
   attention, causing interference. In support of this view, MacLeod and Dunbar (1988) tested the time course of
   interference as a function of practice for a new task (shape naming) and found a gradual reversal of the
   interference pattern, consistent both with a graded notion of automaticity and with the central role of relative
   automaticity in determining interference.
   #+END_QUOTE

*** assumption: practicing leads to automaticity
    
    the central hypothesis

    #+BEGIN_QUOTE
    practice on a task increases its speed of processing and allows it to interfere with tasks of lower processing
    speed. The more practiced tasks are then still the ones causing the most interference. Reading and naming are seen
    as differing only along a practice continuum, with no fundamental asymmetries related, e.g., to word-form encoding
    and production.
    #+END_QUOTE

** Stroop interference in developing or poor readers

   #+BEGIN_QUOTE
   According to Samuels (1999), "poor readers who do not recognize words automatically find [the Stroop color-word test] to be an easy task" (p. 183)
   #+END_QUOTE

   #+BEGIN_QUOTE
   the pattern reported in the literature is that Stroop interference in children learning to read English increases over the course of grades 1-2 (Schiller, 1966) and then diminishes slowly into adulthood, to increase again after age 60 (Comalli, Wapner, & Werner, 1962).
   #+END_QUOTE

   #+BEGIN_QUOTE
   Turning to the performance of poor readers, who are not reading automatically, robust Stroop interference has been repeatedly reported (Alwitt, 1966; Everatt et al., 1997; Helland & Asbjørnsen, 2000; Kelly, Best, & Kirk, 1989; van der Schoot, Licht, Jorsley, & Sergeant, 2000). Moreover, Everatt et al. (1997) found more interference in children with dyslexia than in age-matched controls. Interestingly, in the study of Everatt et al. there was no diVerence in interference between children with dyslexia and reading-level matched, younger controls, suggesting that Stroop interference may be directly related to reading skill regardless of age or status of reading disability. 
   #+END_QUOTE

** methods

*** Greek students in grade 6-8

    Greek orthographic transparency:

    #+BEGIN_QUOTE
    It has been estimated that foundation reading skills in Greek are fully achieved before the end of 1st grade, possibly because of the relative transparency of the Greek orthographic system for reading (Ellis et al., 2004; Seymour et al., 2003) 
    #+END_QUOTE

*** Stroop interference definition

    #+BEGIN_QUOTE
    Stroop interference is calculated here as the difference in time to name the color of all color-word items minus time to name the color of all XX items. 
    #+END_QUOTE

** results: reading disabled (RD) vs nonimpaired (NI)

   RD is a clinical population

   - ~Stroop interference is significantly larger in the RD group than in the NI group, in agreement with the findings of Everatt et al. (1997)~
   - ~stimulus incongruence does not aVect the error rates of RD children more than those of NI children~

** results: general population

     all students from the school sample regardless of evaluation of reading difficulties
     
     #+BEGIN_QUOTE
     Multivariate data analysis procedures are not as robust to deviations from normality as ANOVA is. Therefore, after examining the detailed descriptive statistics, histograms, and Q-Q plots of all the variables, transformations were undertaken to approximate normal distributions for them. Generally, time measures required an inverse transformation whereas error measures required a square root transformation 
     #+END_QUOTE

     #+BEGIN_QUOTE
     relationship between interference and reading skills is a negative one: higher reading skills are associated with less Stroop interference.
     #+END_QUOTE

     #+BEGIN_QUOTE
     Neither age nor any of the intelligence-related measures are related to interference, thus a potential source of
uncontrolled complexity is removed
     #+END_QUOTE

     #+BEGIN_QUOTE
     Moderate correlations are obtained between color naming time (in the control XX condition) and all reading speed
     and accuracy measures. This is expected because naming speed is strongly related to reading ability, particularly
     to reading speed (Leinonen et al., 2001; van den Bos, Zijlstra, & van den Broeck, 2003; Wolf & Bowers, 1999). In
     fact this relation is sufficiently important that recent developments in reading disability indicate that a speed
     measure, as assessed by naming tasks, should be considered alongside phonological skills as a major contributing
     factor to reading skill development (or failure; hence the "double-deficit" theory of reading disability. See Wolf &
     Bowers, 1999; Wolf et al., 2002)
     #+END_QUOTE

     #+BEGIN_QUOTE
     In every case, pseudoword reading time entered the equation first, passing an F-probability criterion of .05, and contributing 8-15% of additional interference variance
     #+END_QUOTE

     #+BEGIN_QUOTE
     Color naming errors were also used originally as a control variable in the first step (analyses not reported) but were not found to contribute any significant variance 
     #+END_QUOTE


*** methodological note
    
    standard Pearson's product-moment coefficients among the transformed variables and non-parametric Spearman's /p/ among the untransformed variables

*** TODO graph on Transformed Stroop interference fig. 2
    
*** color-word naming speed

      #+BEGIN_QUOTE
      color-word naming interference is continuously negatively related to reading skills (better
reading, less interference). The strongest relation is with a straightforward decoding speed
measure, namely pseudoword read time, and this holds after partialling out the eVects of
baseline color naming speed
      #+END_QUOTE


      #+BEGIN_QUOTE
      reading fluency comprises both a speed and an accuracy aspect, with the speed measure more directly relevant
      #+END_QUOTE

*** factor analysis

    #+BEGIN_QUOTE
    The transformed variables were thus entered into a maximum likelihood factor analysis with varimax rotation, in which three factors with eigenvalues greater than 1.0 were extracted, together accounting for 53.3% of the total variance 
    #+END_QUOTE

    #+BEGIN_QUOTE
    these results are not consistent with the hypothesis that correlations of Stroop interference with error and time
    measures reflect a single, simpler underlying dimension of fluency only (i.e., of fast accurate reading). In
    contrast, it seems that interference receives independent contributions from both accuracy and speed
    #+END_QUOTE

*** vis-a-vis developmental / dysfunctional literature

    #+BEGIN_QUOTE
    results are also consistent with the developmental findings (Comalli et al., 1962) that interference decreases with age as children grow up from 7 to 20 years (as well as with the findings of Su, 1997, for picture-word naming interference from 2nd to 6th grade).
    #+END_QUOTE

    #+BEGIN_QUOTE
    because interference is obviously not possible in the absence of any reading ability, the increasing interference through school grades 1 and 2 (Schiller, 1966) most likely reflects the onset of reading, that is, emerging reading skills, and not the gradual attainment of adult fluency. The increased interference reported in old age (over 60 years) may correspond to an overall decrease in reading efficiency 
    #+END_QUOTE

    #+BEGIN_QUOTE
    Ehri and Wilce (1979) found that training recognition accuracy for unfamiliar words increases interference, whereas training recognition speed for familiar words decreases interference 
    #+END_QUOTE

    #+BEGIN_QUOTE
    Stanovich, Cunningham, and West (1981) likewise found increasing interference during the first 6 months of first grade, indicating emerging reading skills, but little further increase in the next 2 months. Presumably, had they continued testing through 3rd or 4th grade they would also have found decreasing interference associated with further automatization of reading skills. 
    #+END_QUOTE

*** Stroop and automaticity

    #+BEGIN_QUOTE
    Stroop interference is taken as an index of the "autonomy associated with automatic processing" (Logan, 1997, p. 126) and not of processing speed (cf. MacLeod, 1991). 
    #+END_QUOTE

    #+BEGIN_QUOTE
    In the context of the instance theory of automaticity (Logan, 1988), Stroop interference hinges on obligatory retrieval, that is, the assumption "that attention to an object or event is sufficient to cause things that were associated with it in the past to be retrieved from memory" (Logan, 1997, p. 131) 
    #+END_QUOTE

    #+BEGIN_QUOTE
    Alternatively, if a mechanism can be postulated to allow suppression of race winners based on task demands, then a
    possible course of processing might be as follows: as soon as obligatory retrieval is active, word reading
    dominates the naming task. Correct performance (color naming) is possible only to the extent that reading
    responses (which typically win the race) can be suppressed at the output stage. Because the response can be
    produced only after inappropriate candidates have been blocked, the time at which the appropriate (color naming)
    response can be selected cannot be earlier than the time at which the dominating (read word) response is
    suppressed. Therefore, slower word reading will lead to later suppression of the read response and later selection
    of the naming response; and thus to slower color naming in the incongruent condition, that is, greater
    interference. This account is similar to the one proposed by Miozzo and Caramazza (2003), where active blocking of
    distractors was hypothesized to explain the finding that distractor word interference in picture naming is
    inversely correlated to the frequency of the distractor.
    #+END_QUOTE

*** reduced inhibition

    #+BEGIN_QUOTE
    in the critical incongruent condition the distribution of participants over number of errors was statistically indistinguishable for the two groups (Table 2). In aging and demented populations, where increased interference is attributed to deficient inhibition, naming errors increase substantially along with increasing interference (Spieler et al., 1996).
    #+END_QUOTE

    #+BEGIN_QUOTE
    If the inhibition hypothesis is the correct explanation of increased interference, despite the lack of an effect on errors, then on the basis of these findings it would have to be expanded to encompass the general population. That is, poor executive inhibition should be found to be continuously associated with increased interference as well as with development of poor reading skills in the general, otherwise cognitively unimpaired, population, resulting in slow, inefficient reading. Whether a priori considered likely or not, and despite being at present less parsimonious than an account of interference that requires consideration of reading skill only, this is an empirically testable hypothesis, and one worth investigating further, in order to elucidate the role of attentional and executive factors of cognitive control in both reading performance and Stroop interference
    #+END_QUOTE

** modeling & simulation

   #+BEGIN_QUOTE
   More recently, Roelofs (2003) has developed a model for the Stroop task based on a more general word production model (WEAVER++; Levelt, Roelofs, & Meyer, 1999). The basic assumption underlying this model is that word reading can directly activate both lemma retrieval and word-form encoding, whereas color naming must pass through conceptual identification before activating lemma retrieval and subsequently word-form encoding. 
   #+END_QUOTE

   #+BEGIN_QUOTE
   Word input ("reading") and color input (via conceptual activation) both contribute activation at the lemma level at which they may compete for selection. Lemma selection is determined by reference to the current task-dependent goal (e.g., "color naming") at a verification stage, so a lemma cannot be selected for response unless it matches the current goal regardless of how much it has been activated. The main diVerence between reading and color naming is the following: because word reading is inherently granted direct access to word forms, it can prevent activation of the word-form response that corresponds to the perceived color. In contrast, color naming cannot prevent activation of the lemma that corresponds to the written word but must wait until the incorrect response is suppressed by blocking rules that prevent goal-inappropriate responses and turn off goal-inappropriate stimulus input. Therefore, in this model, color-word Stroop interference is not so much a matter of experience as it is determined by a fundamental asymmetry between reading and concept naming. Crucially, because of this asymmetry, there is no reverse interference in the model (from an incongruent ink color to the word reading task).
   #+END_QUOTE

   #+BEGIN_QUOTE
   The way the /du/ parameter actually functions in the model is by setting the latency of a blocking rule (P3 in
   Roelofs, 2003). That is, lemmata are activated by their corresponding stimuli for an amount of time equal to /du/, at
   which point P3 applies and blocks the contribution of the task-inappropriate stimulus to lemma activation, thus
   allowing the activation of the task-appropriate (color naming) lemma to exceed the activation of the
   task-inappropriate (reading) one, eventually enabling correct lemma selection
   #+END_QUOTE

*** simulation 1 (a la Roelofs)

    #+BEGIN_QUOTE
    Because word stimuli activate word-form encoding directly, no time is spent on lemma retrieval for the reading task. In contrast, color naming must go through lemma retrieval on the basis of conceptual activation, which is why color naming is slower than word reading. When an incongruent word stimulus is present during the color naming task, then retrieval of the appropriate lemma takes even longer because the word activates an incorrect lemma for the duration of /du/. 
    #+END_QUOTE

    #+BEGIN_QUOTE
    blocking of word input depends on the latency of word form encoding (WFE), which is manipulated to simulate the slow reader, so that /du/ is a function of WFE
    #+END_QUOTE

    #+BEGIN_QUOTE
    after removing a few extreme outliers (two values at z > 4 not shown in the figure), the fit of a linear function (adjusted-R2 of .23 for control, .40 for incongruent, and .28 for interference) was within .02 of the best-fitting monotonic function, indicating that linearity constitutes a reasonable approximation for a wide range of reading performance. 
    #+END_QUOTE

    #+BEGIN_QUOTE
    even though naming speed for a variety of elements, including letters, digits, colors, and object drawings, is related to reading skill, it is the rapid naming of letters (and secondarily of digits) that is most impaired in poor readers (Wolf et al., 2002). Color naming, in particular, is sometimes found not to be strongly related to reading past the ages of the youngest readers (Semrud-Clikeman, Guy, & Griffin, 2000). The reason for these differences seems to lie in the shared cognitive processes (Wile & Borowsky, 2004) and corresponding brain circuits (Misra, Katzir, Wolf, & Poldrack, 2004) between the reading and rapid naming tasks 
    #+END_QUOTE

    #+BEGIN_QUOTE
    the effects of slow reading on color naming may be overestimated. The extent of the overestimate depends on the (unknown) relative contribution of letter-string processing and phonological processing to reading skill variance. 
    #+END_QUOTE

    #+BEGIN_QUOTE
    As a quantitative index of model fit we can calculate the ratio of the slopes: incongruent vs. reading over control vs. reading. This ratio expresses the relative influence of reading skill on the two color naming conditions. The ratio is 2.061 for the simple version of the model (/du/ depending on WFE only), 3.120 for the second version (with /du/ depending on WFE and LVIS in equal proportions) and 2.624 for the human data shown in Fig. 3. 
    #+END_QUOTE

    #+BEGIN_QUOTE
    even though individual letters can be named we have no reason to assume that there is an obligatory or well-practiced letter-naming process to interfere with color naming. In support of the latter assertion, Brown, Roos-Gilbert, & Carr (1995, Experiment 2) have found that rows of X's do not interfere with color naming, even though they produce Stroop dilution. 
    #+END_QUOTE

*** connectionist networks (a la Cohen)

    #+BEGIN_QUOTE
    Color naming, in particular, is sometimes found not to be strongly related to reading past the ages of the youngest readers (Semrud-Clikeman, Guy, & Griffin, 2000). The reason for these differences seems to lie in the shared cognitive processes (Wile & Borowsky, 2004) and corresponding brain circuits (Misra, Katzir, Wolf, & Poldrack, 2004) between the reading and rapid naming tasks 
    #+END_QUOTE

    #+BEGIN_QUOTE
    In this model, Stroop interference arises because of the differential efficiency of the two pathways 
    #+END_QUOTE
    
** conclusion

   #+BEGIN_QUOTE
   We have presented evidence that greater Stroop interference is associated with lower reading skill. In particular, substantial proportions of interference variance can be attributed to decoding speed while additional unique variance is taken up by reading accuracy measures, after controlling for baseline color naming speed. We have interpreted these findings in the context of automatization as supporting a dissociation between obligatoriness and resource efficiency. To account for the effect, a blocking mechanism can be invoked, preventing dominant (obligatory) responses from being produced while allowing their processing speed to determine the non-dominant response latency. 
   #+END_QUOTE

